### ISSUE TITLE
drone secret add issues

### ISSUE THREAD

**Issue by kotedo** [drone/drone-cli#100]
drone cli creates empty secrets if the tags are CAPITAL

Works:
drone secret add --repository MyProjects/theproject --name my_variable --event push --event tag --event deployment --value "TEST 1"

Fails: (empty 'my_variable' secret)
drone secret add --repository MyProjects/theproject --name my_variable --event PUSH --event TAG --event DEPLOYMENT --value "TEST 2"

**Comment by bradrydzewski** [comment]
moving discussion to https://github.com/drone/drone-cli/pull/94

**Comment by kotedo** [comment]
I'd like to know why an all caps tag leads to an empty secret.  I am not sure this is discussed anywhere.
