### ISSUE TITLE
Issue Problem with drone.yml

### ISSUE THREAD

**Issue by julioh** [drone/drone-cli#109]
Hi I used drone cli  i have a problem 
i cant to show all repos this form

drone repo ls - list all repos

and i want know how i get to red  .drone.yml  for any repos

I probe that   drone secret ls  nombrerepo

And they list de secrets.  but i cant show de .drone.yml

Someone any idea to resolv tha problem

Thanks

**Comment by tboerger** [comment]
I would like to help, but I don't really understand what you want to achieve.

Since the issue tracker is reserved for confirmed bugs I ask you to create a thread at https://discourse.drone.io for support.

**Comment by bradrydzewski** [comment]
sorry, I don't think I understand the issue. I think perhaps https://discourse.drone.io is a better place to get support with these types of questions.
