### ISSUE TITLE
Add secret syntax doesn't adhere with new version of Drone CLI  

### ISSUE THREAD

**Issue by darshandeshmukh11** [drone/drone-cli#110]
CLI version - `1.0.1`
Platform - `Windows`, `Linux`

Issue/Error - `Incorrect Usage: flag provided but not defined: -event`
When - `drone secret add --repository "<my-repo>" --name my-secret --event push --event tag --event pull_request --value "a5295d62b571e1d07c5f333fcadd8d"

The above command used to work until version `0.8.6`, I couldn't find any documentation if the syntax is changed with latest version.

**Comment by tboerger** [comment]
It's a major version upgrade, when else should be breaking changes introduced? You can simply type `drone secret add --help` and you would see the available flags.

Besides that, this issue tracker is reserved for confirmed bugs. For support, I kindly ask you to start a thread at https://discourse.drone.io.
