### ISSUE TITLE
Drone log view crashes 

### ISSUE THREAD

**Issue by maximelebastard** [drone/drone-cli#111]
**Drone version**
   0.8.9

**Drone CLI version**
   1.0.1

**Operating system**
 MacOS 10.14 using ZSH

**Expected behavior**
When I run `drone log view maxime/repo 123`, I should see the logs of my build

**Actual behavior**
When I run `drone log view maxime/repo 123`, I get an error
`strconv.Atoi: parsing "": invalid syntax`

Whether the repository or build exists or not.

The issue may come from the slash:

`drone log view maxime` => Error: Invalid or missing repository (e.g. octocat/hello-world).
`drone log view maxime/` => strconv.Atoi: parsing "": invalid syntax
`drone log view maxime/a` => strconv.Atoi: parsing "": invalid syntax
`drone log view maxime/abc 123` => strconv.Atoi: parsing "": invalid syntax

**Comment by maximelebastard** [comment]
Workaround: I rollbacked to drone cli v0.8.6, and it works

**Comment by bradrydzewski** [comment]
The error message is returned because you are missing the step number:

```
$ drone log view --help
NAME:
   drone log view - display the step logs

USAGE:
   drone log view <repo/name> <build> <stage> <step>
```
