### ISSUE TITLE
client error 404: {"message":"Not Found"}

### ISSUE THREAD

**Issue by golyu** [drone/drone-cli#119]
using drone cli 1.0.7
running command 
```
drone secret add --repository drillster/drone-rsync --name rsync_key --data @/root/.ssh/id_rsa
```
got the result
```
client error 404: {"message":"Not Found"}
```

**Comment by madsonic** [comment]
got the same error

**Comment by kikeh** [comment]
I know it's been a while from this.

It happened to me too, my problem was that it was trying to access a private Github repo. But the issue was that my DRONE_TOKEN was out of date. Set my new token as env-var and everything worked just fine.

**Comment by tboerger** [comment]
This is simply the response tied to the connected scm, if the repo doesn't exist: 404. If you don't have access to the repo: 404.

It could get a better formatting, but it's an expected behavior.
