### ISSUE TITLE
jsonnet - line 1: cannot unmarshal !!seq into yaml.RawResource

### ISSUE THREAD

**Issue by TBK** [drone/drone-cli#132]
**Issue:**
When running `drone jsonnet` it can not process "complex" templates resulting in the following error:
```
2019/06/20 00:58:29 yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into yaml.RawResource
```

I have tested with packaged versions on Alpine Linux 3.10, Arch Linux and the latest drone/cli:alpine Docker image all giving the same error.

**Steps to replicate:**
```
wget https://raw.githubusercontent.com/drone/drone/master/.drone.jsonnet
drone jsonnet --stdout
```

**Workaround:**
```
 jsonnet .drone.jsonnet -y > .drone.yml && drone fmt --save
```

**Comment by bradrydzewski** [comment]
You need to use `--stream` if jsonnet is returning an array of pipelines [1]. If you have any further end-user support needs please consider creating a thread in our [forum](https://discourse.drone.io).

[1] https://discourse.drone.io/t/drone-jsonnet-not-working/4500/19
