### ISSUE TITLE
image: registry.test.com/repo_name:${DRONE_COMMIT} still does not work with drone exec if you specify the .env vars into another location.

### ISSUE THREAD

**Issue by jmzoda** [drone/drone-cli#146]
Hello,
image: registry.test.com/repo_name:${DRONE_COMMIT} still does not work with drone exec if you specify the .env vars into another location.

My command is:
echo DRONE_COMMIT=(git rev-parse HEAD)>.drone/env.txt & drone exec --pipeline test --resume-at suite1 --secret-file .drone/secrets.txt --env-file .drone/env.txt --registry=… .drone.yml

As you can see, I use a .drone folder and because of this I get this error message:
mapping values are not allowed in this context

But if I use the .env file at the root of my project, it works which is annoying because the code already uses that file.

Any idea why:
image: registry.test.com/repo_name:${DRONE_COMMIT}
does not use the variables from a file specified with --env-file:
docker exec … --env-file .drone/env.txt

Thank you

**Comment by bradrydzewski** [comment]
lets move this discussion back to your existing discourse thread at https://discourse.drone.io/t/unable-to-specify-the-tag-value-in-an-image-pull/5343.  If nobody has responded to your discourse thread, and this is an urgent matter for you, the next step would be to start debugging the code.
