### ISSUE TITLE
drone jsonnet generates invalid yaml

### ISSUE THREAD

**Issue by fsouza** [drone/drone-cli#149]
Starting in drone 1.1.2, ``drone jsonnet --stream`` is no longer generating a valid .drone.yml file for fake-gcs-server.

- jsonnet source: https://github.com/fsouza/fake-gcs-server/blob/5a9be713ddc39717791d5b187f390415f416bfd3/drone/.drone.jsonnet
- build for [``drone jsonnet --stream`` with drone 1.1.4](https://github.com/fsouza/fake-gcs-server/commit/f949e06341676931e3adb9733359602cd2ef5618) (notice on the diff how required quotes around ``"fsouza/fake-gcs-server:${DRONE_TAG#v}"`` are removed): https://cloud.drone.io/fsouza/fake-gcs-server/118
- fixed by [``drone jsonnet --stream`` with drone 1.0.8](https://github.com/fsouza/fake-gcs-server/commit/5a9be713ddc39717791d5b187f390415f416bfd3): https://cloud.drone.io/fsouza/fake-gcs-server/119

I "bisected" it and it sounds like the issue was introduced in drone 1.1.2? 🤔

**Comment by bradrydzewski** [comment]
I'm not sure I follow the issue.

I am running the latest version of the CLI and I can run `drone jsonnet --stream` and then `drone lint` and I don't get any errors parsing the yaml.  Can you elaborate on what errors you are receiving?

**Comment by fsouza** [comment]
Sure, here's the error as reported by drone: https://cloud.drone.io/fsouza/fake-gcs-server/118

The diff is specifically this change: https://github.com/fsouza/fake-gcs-server/commit/f949e06341676931e3adb9733359602cd2ef5618#diff-619f302e4e51e3be90219185544ffeb1L130-R130

The quotes are required.

**Comment by bradrydzewski** [comment]
quoting this string is not required, it is valid yaml when unquoted.  The problem is that the find/ replace is producing an invalid yaml if DRONE_TAG is empty.

```
image: fsouza/fake-gcs-server:${DRONE_TAG#v}
```

**Comment by fsouza** [comment]
Ohh gotcha 😱 

Let me see if I can figure a workaround.
