### ISSUE TITLE
Fix URL next to description

### ISSUE THREAD

**Issue by schra** [drone/drone-cli#161]
The URL to the right of the repository description is broken. Change http://docs.drone.io/cli-installation/ to https://docs.drone.io/cli/install/

**Comment by phil-davis** [comment]
Note: the link in `README.md`  is correct

**Comment by phil-davis** [comment]
@bradrydzewski this can't be done with a PR - you need to edit the repository "short description".

**Comment by bradrydzewski** [comment]
thanks, updated the description
