### ISSUE TITLE
[Feature Request] Add skip verify to client connections

### ISSUE THREAD

**Issue by toni-moreno** [drone/drone-cli#162]
There is no way to test my drone server from client in a unsecure (test environtment)  instalation.  Should be a way as in any other http tool ( curl --insecure ) or ( git config http.sslVerify false)

When trying with my test server this happened.

```bash
vant@myserver:~/$ export DRONE_SERVER=https://drone.mytest.io
vant@myserver:~/$ export DRONE_TOKEN=cEcLmvCOw7bEAVPzZaSRZruBazonbotg
vant@myserver:~/$ drone info
Get https://drone.mytest.io/api/user: x509: certificate is valid for 067476d965c75fd1f384dcb194b5b4a6.b050635ede917c880c5d6953ccfb7c1f.traefik.default, not drone.mytest.io
```

**Comment by tboerger** [comment]
For the meantime, at least the right domain of the cert should be used. If you are using self-signed certs make sure to create a root cert that is installed on your host, than you are able to work without any insecure flag.

**Comment by toni-moreno** [comment]
I've found in the code https://github.com/drone/drone-cli/blob/master/drone/main.go#L61 that the flag exist

````
vant@server:~/$ export DRONE_SERVER=https://drone.myserver.io
vant@server:~/t$ export DRONE_TOKEN=K5wAhpfnRi3vJI9XI60A4iMAJCtVqUDR
vant@server:~/$ export DRONE_SKIP_VERIFY=true
vant@server:~/t$ drone info
User: gitadmin
Email: git@admin.org
````
