### ISSUE TITLE
Limit step execution in CLI

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-cli#38]
moved from https://github.com/drone/drone/issues/1894

I recommend submitting a pull request that adds --include and --exclude flags. This would enable drone exec --include=build,unit and drone exec --exclude=selenium to limit which of the above steps are executed.

**Comment by tboerger** [comment]
This is already available for a long time:

```
   --include value         Name of steps to include
   --exclude value         Name of steps to exclude
```
