### ISSUE TITLE
`drone sign` command doesn't exist

### ISSUE THREAD

**Issue by jak** [drone/drone-cli#41]
According to http://readme.drone.io/usage/secret-guide/, Drone does not expose secrets to your build unless the Yaml file is signed and verified. However the command to sign does not exist.

Using drone-cli 0.6.0 installed via Homebrew on OS X

**Comment by bradrydzewski** [comment]
`drone sign` was removed in version 0.6 of drone. You can see the release notes at http://docs.drone.io/release-0.6.0 and the updated 0.6 docs at http://docs.drone.io/
