### ISSUE TITLE
same sub-command with list or ls

### ISSUE THREAD

**Issue by ozbillwang** [drone/drone-cli#66]
@bradrydzewski 

Could we have consist commands (list or ls) for `drone build`, `drone repo` and others? Or we should support both `list` and `ls` for compatibility. 

https://github.com/drone/drone-cli/blob/master/drone/repo/repo_list.go#L12

https://github.com/drone/drone-cli/blob/master/drone/build/build_list.go#L12

https://github.com/drone/drone-cli/blob/master/drone/user/user_list.go#L13

https://github.com/drone/drone-cli/blob/master/drone/registry/registry_list.go#L13

https://github.com/drone/drone-cli/blob/master/drone/secret/secret_list.go#L14

**Comment by appleboy** [comment]
see #67
