### ISSUE TITLE
Add a shell to the container

### ISSUE THREAD

**Issue by tonglil** [drone/drone-cli#68]
We should add a shell (`sh`) to this CLI container.

In instances when someone wants to use this image in their pipeline, there is no shell to run `commands:`.

**Comment by tboerger** [comment]
For now I would keep it like it is, until we got native agents for arm/arm64/windows, otherwise we can't update the images automatically.

**Comment by tonglil** [comment]
How do native agents affect this (I do not follow)?

one additional reason to do this is because people currently work around it by making their own images, might as well ship one (with a linux tag or something): https://www.google.com/search?q=drone-cli+site%3Ahub.docker.com

**Comment by bradrydzewski** [comment]
@tonglil we use scratch as the base image for all drone repositories. For individuals or teams that want a shell in their drone images, I have considered shipping alpine tags _in addition to_ the standard images.

For example we would ship:

```sh
drone/cli:latest          # IMAGE drone/ca-certs
drone/cli:linux-arm       # IMAGE drone/ca-certs
drone/cli:linux-arm64     # IMAGE drone/ca-certs
drone/cli:alpine          # IMAGE alpine
```

This is something I considered for drone core in support of https://github.com/drone/drone/issues/1426

```
drone/drone:latest
drone/drone:linux-arm
drone/drone:linux-arm64
drone/drone:alpine

drone/agent:latest
drone/agent:linux-arm
drone/agent:linux-arm64
drone/agent:alpine
```

**Comment by tboerger** [comment]
@bradrydzewski sounds like a good plan
