### ISSUE TITLE
Cannot stop stuck build

### ISSUE THREAD

**Issue by XPLOT1ON** [drone/drone-cli#73]
I cannot stop a stuck build that has been running for multiple days via drone cli. I have tried restarting the drone container but no success

`drone build stop "<repo>" "<commit>"`
This is the error I got
`strconv.Atoi: parsing "<commit>": invalid syntax`

**Comment by tboerger** [comment]
You can only stop build numbers and not commits. And if stop is not enough there is also the build kill command.

**Comment by XPLOT1ON** [comment]
`drone build kill` doesn't exist. Or am I missing something? I've checked for the command in help function. I tried to stop with build number but instead I get this error `client error 400: Cannot cancel a non-running build`. I have confirmed that the test is running by doing `drone build info <repo> <build-number>`

**Comment by tboerger** [comment]
If this command doesn't exist you are not using the latest cli version.

**Comment by XPLOT1ON** [comment]
Solved. Was running v0.7. As stated in the [http://docs.drone.io/cli-installation/](docs) but GitHub release was ahead to v0.8. and upgraded drone server to 0.8.3.

**Comment by tboerger** [comment]
Problem have been solved.
