### ISSUE TITLE
runtime error: panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by shawnzhu** [drone/drone-cli#9]
It keeps throwing this runtime error when performing command `$ drone set-key host/owner/name ~/.ssh/id_rsa`:

```shell
panic: assignment to entry in nil map

goroutine 1 [running]:
net/textproto.MIMEHeader.Set(0x0, 0x585a70, 0xe, 0x208980920, 0x4)
	/usr/src/go/src/net/textproto/header.go:22 +0xce
net/http.Header.Set(0x0, 0x585a70, 0xe, 0x208980920, 0x4)
	/usr/src/go/src/net/http/header.go:31 +0x50
github.com/drone/drone-go/drone.(*Client).run(0x208982940, 0x560f70, 0x3, 0x2088df040, 0x1a, 0x3cd880, 0x2088df060, 0x0, 0x0, 0x0, ...)
	/var/cache/drone/src/github.com/drone/drone-cli/.vendor/src/github.com/drone/drone-go/drone/client.go:83 +0x668
github.com/drone/drone-go/drone.(*RepoService).SetKey(0x2088f4130, 0x7fff5fbfface, 0x4, 0x7fff5fbffad3, 0x5, 0x7fff5fbffad9, 0x4, 0x20897d000, 0x68f, 0x2089a6000, ...)
	/var/cache/drone/src/github.com/drone/drone-cli/.vendor/src/github.com/drone/drone-go/drone/repos.go:52 +0x321
main.setKeyCommandFunc(0x2089a40c0, 0x208982940, 0x0, 0x0)
	/var/cache/drone/src/github.com/drone/drone-cli/drone/keys.go:47 +0x671
main.handle(0x2089a40c0, 0x67ce70)
	/var/cache/drone/src/github.com/drone/drone-cli/drone/handle.go:28 +0xdb
main.func·005(0x2089a40c0)
	/var/cache/drone/src/github.com/drone/drone-cli/drone/keys.go:18 +0x34
github.com/codegangsta/cli.Command.Run(0x577930, 0x7, 0x0, 0x0, 0x6183f0, 0x26, 0x0, 0x0, 0x0, 0x0, ...)
	/var/cache/drone/src/github.com/drone/drone-cli/.vendor/src/github.com/codegangsta/cli/command.go:116 +0x104b
github.com/codegangsta/cli.(*App).Run(0x2089642a0, 0x2088ca000, 0x4, 0x4, 0x0, 0x0)
	/var/cache/drone/src/github.com/drone/drone-cli/.vendor/src/github.com/codegangsta/cli/app.go:168 +0xdce
main.main()
	/var/cache/drone/src/github.com/drone/drone-cli/drone/main.go:47 +0x634

goroutine 7 [runnable]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35
```

I could not figure out why since my test case https://github.com/shawnzhu/drone-go/blob/unittest/drone/client_test.go works very well.

BTW: shall we just remove line 83 of https://github.com/drone/drone-go/drone/client.go ?

**Comment by bradrydzewski** [comment]
darn, I thought we fixed with https://github.com/drone/drone-go/pull/2

I wonder if we should just do `req.Header = new(http.Header)`? I'm not on my work laptop at the moment, but will try a bit later to see if I can get to the bottom of it.

**Comment by shawnzhu** [comment]
it looks similar to #1001

**Comment by shawnzhu** [comment]
@bradrydzewski it does create Header map uninitialized via `make(Header)` in helper `http.NewRequest`. see [golang/go#0db312b6a854cc75aa88899865560a7ddcdf9f07](https://github.com/golang/go/commit/0db312b6a854cc75aa88899865560a7ddcdf9f07), it should work since `make` is used when you need to create maps.

what bothers me is the drone client code works in https://github.com/shawnzhu/drone-go/blob/unittest/drone/client_test.go no idea how to keep forward

**Comment by shawnzhu** [comment]
it works for me when reinstall drone via `brew` after cleaning local brew cache at `/Library/Caches/Homebrew/drone-64.tar.gz`. sorry for the trouble
