### ISSUE TITLE
[Bug] Cannot set $DRONE_REPO_OWNER for drone exec

### ISSUE THREAD

**Issue by hjkatz** [drone/drone-cli#93]
Cannot set the environment variable `DRONE_REPO_OWNER` for use with `drone exec --local` because it appears to have been skipped here: https://github.com/drone/drone-cli/blob/master/drone/exec/exec.go#L129

**Comment by amaya382** [comment]
Since this link is not permanent, I cannot figure out anything
Anyway, we can set `DRONE_REPO_OWNER` via an environment variable like the following
`DRONE_REPO_OWNER=foo drone exec`

**Comment by hjkatz** [comment]
This may have been fixed. In the past it was not respecting the env var being set due to the env var being skipped in the pflag processing. It looks like that is gone now because it's using env vars for all the configuration with string pflags as a backup, but I'd have to try it out to be sure. Feel free to close if you believe this is working.

**Comment by tboerger** [comment]
`DRONE_REPO_OWNER` doesn't exist anymore, it's `DRONE_REPO` and should work totally fine. Closing this issue now.
