### ISSUE TITLE
Disable http.Client auto-redirect

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-cli#96]
Use a custom redirect policy to disable HTTP redirects by default.

```
client.CheckRedirect = func(*http.Request, []*http.Request) error {
  return fmt.Errorf("Attempting to redirect HTTP requests. Did you configure the correct DRONE_SERVER address?")
}
```

This will help prevent a common configuration error where the DRONE_SERVER is set to the HTTP url and is automatically redirected to the HTTPS url by the server or a reverse proxy. The Go client, by default, automatically converts POST requests to GET requests on redirect, which causes unexpected behavior and can be difficult to troubleshoot. A custom policy that errors on redirect should make this easier for end-users to resolve.

cc @snoby

**Comment by snoby** [comment]
Thank you @brad	 - This will make solving the configuration issue easier for the next person.
🥇

**Comment by tboerger** [comment]
I have created #157 to get this solved.
