### ISSUE TITLE
drone secret add

### ISSUE THREAD

**Issue by pixie79** [drone/drone-cli#97]
Drone secret add should be immutable, in other words I should be able to add the same secret many times with the same name. Currently Drone rejects with a duplicate secret rather than updating.

Either that or there should be a switch to allow it to be add or update.

There would then be no requirement for an update command. This is needed because the output of 'drone secret ls' is not parsable easily.

**Comment by tboerger** [comment]
The drone secret ls command for a format flag, that works really good for parsing the output.

IMHO it's totally fine that add errors if the secret already exists. Otherwise the name should be simply wrong.
